### ISSUE TITLE
Support Go 1.5 `vendor/` experiment.

### ISSUE THREAD

**Issue by abourget** [rogpeppe/godef#13]
Does `godef` need to be altered for that ?

**Comment by rgarcia** [comment]
As far as I can tell, godef does not support vendored files:

```go
// ~/go/src/test/test.go
package main

import "a"

func main() {
	println(a.HelloFromA)
}
```

```go
// ~/go/src/test/vendor/a/a.go
package a

var HelloFromA = "Hello!"
```

```bash
$ export GO15VENDOREXPERIMENT=1
$ go run test.go
Hello!
$ godef -f test.go "a.HelloFromA"
parseLocalPackage error: no more package files found
godef: no declaration found for a.HelloFromA
```

**Comment by rogpeppe** [comment]
Yeah, this needs to be fixed.

**Comment by abourget** [comment]
I have a PR for that, don't I ? My fork has that implemented.

Le jeu. 14 janv. 2016 06:47, Roger Peppe <notifications@github.com> a
écrit :

**Comment by douglarek** [comment]
@rogpeppe 1.6 has released, any plan for this issue ?

**Comment by gonzaloserrano** [comment]
Also interested :-)

**Comment by douglarek** [comment]
@abourget would you please make a PR based the latest codes ?

**Comment by missedone** [comment]
link PR #25

**Comment by dingyaguang117** [comment]
+1

**Comment by douglarek** [comment]
Maybe this project is dead, It's time to have a fork !!!

**Comment by missedone** [comment]
@douglarek fork is always the last option...

@rogpeppe , maybe it'd be better if you could elect some Collaborator to help you manage this repo (e.g. maintain, review the PRs, etc.) if you're too busy.
thanks

**Comment by pwaller** [comment]
Has #33 finally fixed this?

**Comment by douglarek** [comment]
@pwaller yes, master has fixed this issue.

**Comment by rogpeppe** [comment]
Fixed by #33. Sorry for the long wait, guys :)

**Comment by tiborvass** [comment]
@rogpeppe the example in https://github.com/rogpeppe/godef/issues/13#issuecomment-168434693 still doesn't seem to work.

**Comment by rogpeppe** [comment]
It works when an absolute path name is used for the go file.
Perhaps godef should make the file name absolute before considering it.
